### ISSUE TITLE
Game crash helpp, fix this in next update, LOG: in comments

### ISSUE THREAD

**Issue by FrogPlayzz** [Soro335/WilderWild#13] opened 2022-04-25 14:47 UTC
[17:06:23] [main/INFO]: Loading Minecraft 22w16b with Fabric Loader 0.14.2
[17:06:24] [main/INFO]: Loading 47 mods:
	- fabric 0.51.2+1.19
	- fabric-api-base 0.4.5+ec94c6f6e0 via fabric
	- fabric-api-lookup-api-v1 1.6.1+ec94c6f6e0 via fabric
	- fabric-biome-api-v1 9.0.4+8eae4510e0 via fabric
	- fabric-blockrenderlayer-v1 1.1.13+3ac43d95e0 via fabric
	- fabric-command-api-v1 1.1.12+ec94c6f6e0 via fabric
	- fabric-commands-v0 0.2.11+b4f4f6cde0 via fabric
	- fabric-containers-v0 0.1.22+d7c144a8e0 via fabric
	- fabric-content-registries-v0 3.0.9+d82b9392e0 via fabric
	- fabric-convention-tags-v1 1.0.2+93eb6f91e0 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d95e0 via fabric
	- fabric-dimensions-v1 2.1.20+ec94c6f6e0 via fabric
	- fabric-entity-events-v1 1.4.11+ec94c6f6e0 via fabric
	- fabric-events-interaction-v0 0.4.22+a67d2aa5e0 via fabric
	- fabric-events-lifecycle-v0 0.2.17+ec94c6f6e0 via fabric
	- fabric-game-rule-api-v1 1.0.14+ec94c6f6e0 via fabric
	- fabric-item-api-v1 1.4.2+ec94c6f6e0 via fabric
	- fabric-item-groups-v0 0.3.17+ec94c6f6e0 via fabric
	- fabric-key-binding-api-v1 1.0.13+ec94c6f6e0 via fabric
	- fabric-keybindings-v0 0.2.11+b4f4f6cde0 via fabric
	- fabric-lifecycle-events-v1 2.0.4+2d83e92ce0 via fabric
	- fabric-loot-tables-v1 1.0.12+d7c144a8e0 via fabric
	- fabric-mining-level-api-v1 2.1.1+0c7c3953e0 via fabric
	- fabric-models-v0 0.3.9+8eae4510e0 via fabric
	- fabric-networking-api-v1 1.0.22+ec94c6f6e0 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cde0 via fabric
	- fabric-object-builder-api-v1 3.1.2+ec94c6f6e0 via fabric
	- fabric-particles-v1 1.0.2+8eae4510e0 via fabric
	- fabric-registry-sync-v0 0.9.9+ec94c6f6e0 via fabric
	- fabric-renderer-api-v1 1.0.2+8eae4510e0 via fabric
	- fabric-renderer-indigo 0.5.1+ec94c6f6e0 via fabric
	- fabric-renderer-registries-v1 3.2.13+b4f4f6cde0 via fabric
	- fabric-rendering-data-attachment-v1 0.3.8+d7c144a8e0 via fabric
	- fabric-rendering-fluids-v1 2.0.3+54e5b2ece0 via fabric
	- fabric-rendering-v0 1.1.15+b4f4f6cde0 via fabric
	- fabric-rendering-v1 1.10.9+ec94c6f6e0 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa66e0 via fabric
	- fabric-resource-loader-v0 0.4.24+ec94c6f6e0 via fabric
	- fabric-screen-api-v1 1.0.17+ec94c6f6e0 via fabric
	- fabric-screen-handler-api-v1 1.2.1+ec94c6f6e0 via fabric
	- fabric-textures-v0 1.0.13+3ac43d95e0 via fabric
	- fabric-transfer-api-v1 1.6.1+ec94c6f6e0 via fabric
	- fabric-transitive-access-wideners-v1 1.0.2+614e5400e0 via fabric
	- fabricloader 0.14.2
	- java 17
	- minecraft 1.19-alpha.22.16.b
	- wilderwild 0.1.0
[17:06:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/vilih/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:06:25] [main/INFO]: Compatibility level set to JAVA_16
[17:06:25] [main/INFO]: Compatibility level set to JAVA_17
[17:06:29] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[17:06:30] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:06:48] [main/INFO]: Building optimized datafixer
[17:07:02] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:07:03] [Render thread/INFO]: Setting user: MrCat2022
[17:07:08] [Render thread/INFO]: Registering Blocks for wilderwild
[17:07:08] [Render thread/INFO]: [STDOUT]: Registering WildConfiguredFeatures for wilderwild
[17:07:09] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[17:07:11] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[17:07:22] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:07:23] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Wilder Wild)
[17:07:24] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:335) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zfd001$onStart(class_310.java:4875) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:703) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.2.jar:?]
[17:07:24] [Render thread/INFO]: Stopping!
[17:07:25] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1037) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1013) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.2.jar:?]
[17:07:26] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

**Comment by MerpisMe** [comment] 2022-04-25 14:50
Duplicate of #12

**Closed by MerpisMe** 2022-04-25 14:50 UTC
Labels: duplicate
